#!/bin/bash
OPENSUSE_VENDOR="OPENSUSE"
OPENSUSE_BASE_URL='http://download.opensuse.org/ports/aarch64'
OPENSUSE_RELEASE_IGNORE="debug\|distribution\|factory\|source\|update"
OPENSUSE_VARIANT_IGNORE="Snapshot"
OPENSUSE_checkInput(){
	:
}
OPENSUSE_main(){
	OPENSUSE_checkInput "$@"
	local path=("${@:1:1}")
	local path=$(IFS=/; echo "${path[*]}")
	local path_url="$OPENSUSE_BASE_URL/$path"
	if [ ! -z "$1" ]; then
		local path_url="$path_url/appliances"
	fi
	echo $path_url
	local html=$(wget -O - "$path_url/")
	if [ $? -ne 0 ]; then
		echo "$VENDOR $@ is not supported." >&2
		return 1
	fi
	if [ -z "$1" ]; then
		local html_xpath='//a[not(starts-with(@href, "/")) and not(contains(@href, "?")) and substring(normalize-space(text()), string-length(normalize-space(text())) - string-length("/") + 1, string-length("/")) = "/"]/text()'
	else
		local filename_match=".$LDP_ARCH_CPU.raw.xz"
		local html_xpath="//a[substring(@href, string-length(@href) - string-length('$filename_match') + 1, string-length('$filename_match')) = '$filename_match']/@href"
	fi
	local results="$(echo "$html" | xmllint --html --xpath "$html_xpath" - 2>/dev/null)"
	if [ $? -ne 0 ] || [ -z "$results" ]; then
		echo "$VENDOR $@ is not supported." >&2
		return 1
	fi
	if [ -z "$1" ]; then
		local results="$(echo "$results" | sed 's/\/$//')"
		echo "$results" | grep -v "$OPENSUSE_RELEASE_IGNORE" | tail -n 3
		return $LDP_AUTO
	fi
	local results="$(echo "$results" | sed 's/^ href=".\///;s/"$//' | grep -v "$OPENSUSE_VARIANT_IGNORE" | grep efi | uniq)"
	if [ -z "$2" ]; then
		echo "$results"
		return $LDP_AUTO
	fi
	local image="$(echo "$results" | grep -i "$2" | head -n 1)"
	if [ -z "$image" ]; then
		echo "$VENDOR $@ is not supported." >&2
		exit 1
	fi
	local image_url="$path_url/$image"
	echo "Using image: $image_url" >&2
	if [ -z "$3" ]; then
		echo "$LDP_BLOCK_devices"
		return $LDP_AUTO
	elif [ -z "$(echo \"$LDP_BLOCK_devices\" | grep $3)" ]; then
		echo "$3 is not in:"
		echo "$LDP_BLOCK_devices"
		exit 1
	fi
	LDP_BLOCK_flashURLRaw "$image_url" "$3"
	if [ ! -z "$LDP_GUI_RUN" ]; then
		rm "$LDP_GUI_RUN"
		unset LDP_GUI_RUN
	fi
}
