#!/bin/bash
#
# time is necessary for https

LDP_TIME_waitForSync(){
	SECONDS=0
	local linefeed=0
	while [ ! -e "/run/systemd/timesync/synchronized" ]; do
		echo -en "\rSynchronizing System Time: ${SECONDS}s" >&2
		local linefeed=1
	done
	if [ "$linefeed" -eq 1 ]; then
		echo >&2
	fi
}
